version: '2.3'

x-user:
  &default-user
    # The default user under which the containers should run. Change this if you are on linux and run with another user than id `1000`
    user: '1000'

services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
    image: denkins:latest
    labels:
      # Lagoon Labels
      lagoon.type: cli-persistent
    volumes_from: # mount the ssh-agent from the pygmy or cachalot ssh-agent
      - container:amazeeio-ssh-agent
    ports:
      - "50000:50000"
      - "8080:8080"
    volumes:
      - "/tmp/jenkins_lts:/var/jenkins_home"
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - SSH_AUTH_SOCK=/tmp/ssh-agent
